name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        uses: cardinalby/schema-validator-action@v1
        with:
          file: tags.yml
          schema: schema/tags.json
